# Generated by Django 3.2.18 on 2023-04-21 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classbooking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 21)),
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(default='Studio A', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='test_class', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='spaces',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 21, 16, 34, 24, 389117)),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.CharField(default='test_user', max_length=50),
        ),
    ]
