# Generated by Django 3.2.18 on 2023-04-22 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classbooking_app', '0002_auto_20230421_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test_class', max_length=50)),
                ('date', models.DateField(default=datetime.date(2023, 4, 22))),
                ('time', models.TimeField(default=datetime.datetime(2023, 4, 22, 13, 58, 10, 640547))),
                ('spaces', models.IntegerField(default=25)),
                ('location', models.CharField(default='Studio A', max_length=50)),
                ('running', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 22)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 22, 13, 58, 10, 640073)),
        ),
    ]
