# Generated by Django 3.2.18 on 2023-04-22 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classbooking_app', '0004_auto_20230422_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='attendees',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 22, 15, 29, 38, 31877)),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 22, 15, 29, 38, 32350)),
        ),
    ]
