# Generated by Django 3.2.18 on 2023-04-22 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classbooking_app', '0005_auto_20230422_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 22, 15, 34, 10, 726770)),
        ),
        migrations.AlterField(
            model_name='session',
            name='attendees',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 22, 15, 34, 10, 727440)),
        ),
    ]
