# Generated by Django 3.2.18 on 2023-04-22 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classbooking_app', '0006_auto_20230422_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 22, 15, 36, 23, 541990)),
        ),
        migrations.AlterField(
            model_name='session',
            name='attendees',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 22, 15, 36, 23, 542451)),
        ),
    ]
