# Generated by Django 3.2.18 on 2023-04-23 20:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classbooking_app', '0008_auto_20230422_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='location',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='running',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='spaces',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='fk',
            field=models.ForeignKey(default=145040, on_delete=django.db.models.deletion.CASCADE, to='classbooking_app.session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 23)),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 23, 20, 50, 2, 727980)),
        ),
    ]
