# Generated by Django 3.2.18 on 2023-04-24 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classbooking_app', '0009_auto_20230423_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='fk',
            new_name='session_id',
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 24)),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 24, 9, 58, 27, 943924)),
        ),
    ]
