# Generated by Django 3.2.18 on 2023-04-24 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classbooking_app', '0010_auto_20230424_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 24, 10, 59, 49, 416495)),
        ),
    ]
