# Generated by Django 3.2.18 on 2023-04-24 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classbooking_app', '0011_alter_session_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='session_id',
            new_name='session',
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 24, 11, 46, 48, 713875)),
        ),
    ]
