# Generated by Django 3.2.18 on 2023-04-27 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classbooking_app', '0012_auto_20230424_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test_class', max_length=50)),
                ('description', models.CharField(default='test_image', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 27)),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 27, 11, 0, 17, 147565)),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classbooking_app.activity'),
        ),
    ]
