# Generated by Django 3.2.18 on 2023-04-27 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classbooking_app', '0013_auto_20230427_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.CharField(default='test_image', max_length=10),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(default='test_description', max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 27, 11, 1, 39, 407550)),
        ),
    ]
