# Generated by Django 3.2.18 on 2023-04-27 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classbooking_app', '0015_auto_20230427_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='attendees',
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 27, 11, 12, 39, 567126)),
        ),
    ]
