# Generated by Django 3.2.18 on 2023-05-25 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classbooking_app', '0026_auto_20230525_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(default='test_description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 25, 11, 2, 56, 58581)),
        ),
    ]
