# Generated by Django 3.2.18 on 2023-05-25 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classbooking_app', '0031_auto_20230525_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.CharField(default='test_description', max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 25, 16, 15, 51, 85800)),
        ),
    ]
