# Generated by Django 3.2.19 on 2023-05-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classbooking_app', '0033_auto_20230525_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='image',
        ),
    ]
